const productsData = [
    {
      brand: "MOTOROLA",
      name: "g24 Power (Glacier Blue, 128 GB)",
      subtitle: "Nice phone",
      image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/d/i/m/g24-pb1c0001in-motorola-original-imagxm3bhyh7ywnr.jpeg?q=70",
      price: 110000,
      discount: 40,
    },
    {
      brand: "Samsung",
      name: "Galaxy S21 Ultra 5G (Phantom Silver, 128 GB)",
      subtitle: "Stunning camera",
      image: "https://rukminim2.flixcart.com/image/312/312/kjvrdzk0/mobile/y/n/z/samsung-galaxy-s21-ultra-sm-g998bzsginu-original-imafzchbfk4zg9ga.jpeg?q=70",
      price: 125000,
      discount: 35,
    },
    {
      brand: "Apple",
      name: "iPhone 13 Pro (Graphite, 128 GB)",
      subtitle: "Advanced features",
      image: "https://rukminim2.flixcart.com/image/312/312/ktketu80/mobile/m/t/r/iphone-13-pro-mlvv3hn-a-apple-original-imag6vpb7zg6bnvb.jpeg?q=70",
      price: 130000,
      discount: 20,
    },
    {
      brand: "OnePlus",
      name: "9 Pro 5G (Stellar Black, 256 GB)",
      subtitle: "Fast and smooth",
      image: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/n/r/r/-original-imagdm3mhu4hu4xx.jpeg?q=70",
      price: 95000,
      discount: 15,
    },
    {
      brand: "Xiaomi",
      name: "Mi 11X (Cosmic Black, 128 GB)",
      subtitle: "Flagship killer",
      image: "https://rukminim2.flixcart.com/image/312/312/kp78e4w0/mobile/b/2/u/11x-11x-mi-original-imag3hqsshfzpv4u.jpeg?q=70",
      price: 35000,
      discount: 25,
    },
    {
      brand: "Realme",
      name: "GT 5G (Dashing Blue, 128 GB)",
      subtitle: "Performance beast",
      image: "https://rukminim2.flixcart.com/image/312/312/l3rmzrk0/mobile/z/i/t/-original-imagetme2k2rva45.jpeg?q=70",
      price: 30000,
      discount: 30,
    },
    {
      brand: "Google",
      name: "Pixel 6 (Stormy Black, 128 GB)",
      subtitle: "Pure Android experience",
      image: "https://m.media-amazon.com/images/I/41MF9mpSoxL._AC_UY218_.jpg",
      price: 80000,
      discount: 10,
    },
    {
      brand: "Vivo",
      name: "V21 5G (Sunset Dazzle, 128 GB)",
      subtitle: "Slim and stylish",
      image: "https://rukminim2.flixcart.com/image/312/312/ko1smfk0/mobile/0/y/p/v21-5g-pd2083f-ex-vivo-original-imag2kzczrpgc6s3.jpeg?q=70",
      price: 40000,
      discount: 20,
    },
    {
      brand: "Oppo",
      name: "Reno6 Pro 5G (Aurora, 256 GB)",
      subtitle: "Capture every moment",
      image: "https://rukminim2.flixcart.com/image/312/312/kr2e3680/mobile/l/p/k/reno6-pro-5g-cph2249-oppo-original-imag4xpc6mc62mzq.jpeg?q=70",
      price: 55000,
      discount: 15,
    },
    {
      brand: "Asus",
      name: "ROG Phone 5 (Phantom Black, 256 GB)",
      subtitle: "Built for gamers",
      image: "https://rukminim2.flixcart.com/image/312/312/ky7lci80/mobile/l/w/z/-original-imagahvnzfgdg8jy.jpeg?q=70",
      price: 70000,
      discount: 25,
    },
  ];
  
  export default productsData;